{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:BlockTest", "name": "test_verify_merkle_proof", "time": 0.00041747093200683594, "type": "failure", "errtype": "builtins.AssertionError", "message": "None is not true", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/jonastest00/merkle-proofs-verification-jsong-programming-blockchain-demo/test/index_test.py\", line 18, in test_verify_merkle_proof\n    self.assertTrue(proof.verify())\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\nAssertionError: None is not true\n"}]}